Repository hiero-ledger/hiero-sdk-java, pull requests merged in 2024-08, with the labels that each got.

#1922 chore: update directory for gradle in dependabot
  .github/dependabot.yml
Labels: github_actions

#1892 feat(HIP-869): Dynamic Address Book - Stage 1 - HAPI Endpoints
  examples/src/main/java/com/hedera/hashgraph/sdk/examples/DynamicAddressBookExample.java
  sdk/src/main/java/com/hedera/hashgraph/sdk/Endpoint.java
  sdk/src/main/java/com/hedera/hashgraph/sdk/IPv4Address.java
  sdk/src/main/java/com/hedera/hashgraph/sdk/IPv4AddressPart.java
  sdk/src/main/java/com/hedera/hashgraph/sdk/NodeCreateTransaction.java
  sdk/src/main/java/com/hedera/hashgraph/sdk/NodeDeleteTransaction.java
  sdk/src/main/java/com/hedera/hashgraph/sdk/NodeUpdateTransaction.java
  sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java
  sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceipt.java
  sdk/src/test/java/com/hedera/hashgraph/sdk/AddressBookQueryMockTest.java
  sdk/src/test/java/com/hedera/hashgraph/sdk/NodeCreateTransactionTest.java
  sdk/src/test/java/com/hedera/hashgraph/sdk/NodeCreateTransactionTest.snap
  sdk/src/test/java/com/hedera/hashgraph/sdk/NodeDeleteTransactionTest.java
  sdk/src/test/java/com/hedera/hashgraph/sdk/NodeDeleteTransactionTest.snap
  sdk/src/test/java/com/hedera/hashgraph/sdk/NodeUpdateTransactionTest.java
  sdk/src/test/java/com/hedera/hashgraph/sdk/NodeUpdateTransactionTest.snap
  sdk/src/test/java/com/hedera/hashgraph/sdk/TransactionReceiptTest.java
  sdk/src/test/java/com/hedera/hashgraph/sdk/TransactionReceiptTest.snap
  sdk/src/test/java/com/hedera/hashgraph/sdk/TransactionRecordTest.snap
Labels: enhancement

#1967 fix: handle `FEE_SCHEDULE_FILE_PART_UPLOADED` status
  sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceipt.java
  sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/FileUpdateIntegrationTest.java
Labels: bug

#1974 ci: update workflows to use latitude.sh based runners
  .github/workflows/build.yml
  .github/workflows/disabled/main.yml
  .github/workflows/disabled/previewnet.yml
  .github/workflows/disabled/testnet.yml
  .github/workflows/pages.yml
  .github/workflows/release-artifacts.yml
Labels: enhancement
